//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNumber
    {
        public int Id { get; set; }
        public string DocumentCode { get; set; }
        public int CurrentSequence { get; set; }
        public string CurrentNumber { get; set; }
        public string Description { get; set; }
    }
}
