//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GlobalSolusindoDb : DbContext
    {
        public GlobalSolusindoDb()
            : base("name=GlobalSolusindoDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentNumber> DocumentNumbers { get; set; }
        public virtual DbSet<tblM_Area> tblM_Area { get; set; }
        public virtual DbSet<tblM_Aset> tblM_Aset { get; set; }
        public virtual DbSet<tblM_AsetKategori> tblM_AsetKategori { get; set; }
        public virtual DbSet<tblM_AuthParam> tblM_AuthParam { get; set; }
        public virtual DbSet<tblM_BTS> tblM_BTS { get; set; }
        public virtual DbSet<tblM_BTSStatus> tblM_BTSStatus { get; set; }
        public virtual DbSet<tblM_BTSTechnology> tblM_BTSTechnology { get; set; }
        public virtual DbSet<tblM_Cabang> tblM_Cabang { get; set; }
        public virtual DbSet<tblM_CostKategori> tblM_CostKategori { get; set; }
        public virtual DbSet<tblM_DeliveryArea> tblM_DeliveryArea { get; set; }
        public virtual DbSet<tblM_IssueType> tblM_IssueType { get; set; }
        public virtual DbSet<tblM_IzinCutiStatus> tblM_IzinCutiStatus { get; set; }
        public virtual DbSet<tblM_KategoriJabatan> tblM_KategoriJabatan { get; set; }
        public virtual DbSet<tblM_Kota> tblM_Kota { get; set; }
        public virtual DbSet<tblM_MappingRoleToRoleGroup> tblM_MappingRoleToRoleGroup { get; set; }
        public virtual DbSet<tblM_MappingUserToAuthParam> tblM_MappingUserToAuthParam { get; set; }
        public virtual DbSet<tblM_MappingUserToRoleGroup> tblM_MappingUserToRoleGroup { get; set; }
        public virtual DbSet<tblM_Menu> tblM_Menu { get; set; }
        public virtual DbSet<tblM_Operator> tblM_Operator { get; set; }
        public virtual DbSet<tblM_PMHistori> tblM_PMHistori { get; set; }
        public virtual DbSet<tblM_Project> tblM_Project { get; set; }
        public virtual DbSet<tblM_Role> tblM_Role { get; set; }
        public virtual DbSet<tblM_RoleGroup> tblM_RoleGroup { get; set; }
        public virtual DbSet<tblM_Status> tblM_Status { get; set; }
        public virtual DbSet<tblM_Technology> tblM_Technology { get; set; }
        public virtual DbSet<tblM_TipePekerjaan> tblM_TipePekerjaan { get; set; }
        public virtual DbSet<tblM_User> tblM_User { get; set; }
        public virtual DbSet<tblM_UserDetail> tblM_UserDetail { get; set; }
        public virtual DbSet<tblM_Vendor> tblM_Vendor { get; set; }
        public virtual DbSet<tblT_AsetHistori> tblT_AsetHistori { get; set; }
        public virtual DbSet<tblT_CheckIn> tblT_CheckIn { get; set; }
        public virtual DbSet<tblT_Cost> tblT_Cost { get; set; }
        public virtual DbSet<tblT_IzinCuti> tblT_IzinCuti { get; set; }
        public virtual DbSet<tblT_PO> tblT_PO { get; set; }
        public virtual DbSet<tblT_SOW> tblT_SOW { get; set; }
        public virtual DbSet<tblT_SOWAssign> tblT_SOWAssign { get; set; }
        public virtual DbSet<tblT_SOWIssue> tblT_SOWIssue { get; set; }
        public virtual DbSet<tblT_SOWResult> tblT_SOWResult { get; set; }
        public virtual DbSet<tblT_SOWStatus> tblT_SOWStatus { get; set; }
        public virtual DbSet<tblT_SOWTrack> tblT_SOWTrack { get; set; }
        public virtual DbSet<tblT_SOWTrackResult> tblT_SOWTrackResult { get; set; }
        public virtual DbSet<tblT_UserHistori> tblT_UserHistori { get; set; }
        public virtual DbSet<tblT_UserPayroll> tblT_UserPayroll { get; set; }
    
        public virtual ObjectResult<GetTaskList_Result> GetTaskList(Nullable<int> userID, Nullable<int> statusSOW)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var statusSOWParameter = statusSOW.HasValue ?
                new ObjectParameter("statusSOW", statusSOW) :
                new ObjectParameter("statusSOW", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTaskList_Result>("GetTaskList", userIDParameter, statusSOWParameter);
        }
    
        public virtual ObjectResult<GetTimesheetDaily_Result> GetTimesheetDaily(Nullable<int> userID, Nullable<int> month, Nullable<int> year, Nullable<int> day)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTimesheetDaily_Result>("GetTimesheetDaily", userIDParameter, monthParameter, yearParameter, dayParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> GetTimesheetMonthly(Nullable<int> userID, Nullable<int> month, Nullable<int> year)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("GetTimesheetMonthly", userIDParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<GetTimesheetMonthlyV2_Result> GetTimesheetMonthlyV2(Nullable<int> userId, Nullable<int> month, Nullable<int> year)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTimesheetMonthlyV2_Result>("GetTimesheetMonthlyV2", userIdParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<usp_GetActivities_Result> usp_GetActivities(Nullable<int> user_FK)
        {
            var user_FKParameter = user_FK.HasValue ?
                new ObjectParameter("User_FK", user_FK) :
                new ObjectParameter("User_FK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetActivities_Result>("usp_GetActivities", user_FKParameter);
        }
    
        public virtual ObjectResult<usp_GetDailyTask_Result> usp_GetDailyTask(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDailyTask_Result>("usp_GetDailyTask", keywordParameter);
        }
    
        public virtual ObjectResult<usp_GetNetworkTask_Result> usp_GetNetworkTask(Nullable<int> userFk, Nullable<int> sowFk)
        {
            var userFkParameter = userFk.HasValue ?
                new ObjectParameter("userFk", userFk) :
                new ObjectParameter("userFk", typeof(int));
    
            var sowFkParameter = sowFk.HasValue ?
                new ObjectParameter("sowFk", sowFk) :
                new ObjectParameter("sowFk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetNetworkTask_Result>("usp_GetNetworkTask", userFkParameter, sowFkParameter);
        }
    
        public virtual ObjectResult<usp_GetSowAssign_Result> usp_GetSowAssign(Nullable<int> sOW_FK)
        {
            var sOW_FKParameter = sOW_FK.HasValue ?
                new ObjectParameter("SOW_FK", sOW_FK) :
                new ObjectParameter("SOW_FK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSowAssign_Result>("usp_GetSowAssign", sOW_FKParameter);
        }
    
        public virtual ObjectResult<string> usp_GetDocNumber(string documentCode, Nullable<bool> updateCurrentNumber)
        {
            var documentCodeParameter = documentCode != null ?
                new ObjectParameter("documentCode", documentCode) :
                new ObjectParameter("documentCode", typeof(string));
    
            var updateCurrentNumberParameter = updateCurrentNumber.HasValue ?
                new ObjectParameter("updateCurrentNumber", updateCurrentNumber) :
                new ObjectParameter("updateCurrentNumber", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetDocNumber", documentCodeParameter, updateCurrentNumberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Count_Po()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Count_Po");
        }
    }
}
