//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlobalSolusindoDb : DbContext
    {
        public GlobalSolusindoDb()
            : base("name=GlobalSolusindoDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblM_Area> tblM_Area { get; set; }
        public virtual DbSet<tblM_Aset> tblM_Aset { get; set; }
        public virtual DbSet<tblM_AsetKategori> tblM_AsetKategori { get; set; }
        public virtual DbSet<tblM_AuthParam> tblM_AuthParam { get; set; }
        public virtual DbSet<tblM_BTS> tblM_BTS { get; set; }
        public virtual DbSet<tblM_BTSStatus> tblM_BTSStatus { get; set; }
        public virtual DbSet<tblM_Cabang> tblM_Cabang { get; set; }
        public virtual DbSet<tblM_CostKategori> tblM_CostKategori { get; set; }
        public virtual DbSet<tblM_DeliveryArea> tblM_DeliveryArea { get; set; }
        public virtual DbSet<tblM_IzinCutiStatus> tblM_IzinCutiStatus { get; set; }
        public virtual DbSet<tblM_KategoriJabatan> tblM_KategoriJabatan { get; set; }
        public virtual DbSet<tblM_Kota> tblM_Kota { get; set; }
        public virtual DbSet<tblM_MappingRoleToRoleGroup> tblM_MappingRoleToRoleGroup { get; set; }
        public virtual DbSet<tblM_MappingUserToAuthParam> tblM_MappingUserToAuthParam { get; set; }
        public virtual DbSet<tblM_MappingUserToRoleGroup> tblM_MappingUserToRoleGroup { get; set; }
        public virtual DbSet<tblM_Operator> tblM_Operator { get; set; }
        public virtual DbSet<tblM_PMHistori> tblM_PMHistori { get; set; }
        public virtual DbSet<tblM_Project> tblM_Project { get; set; }
        public virtual DbSet<tblM_Role> tblM_Role { get; set; }
        public virtual DbSet<tblM_RoleGroup> tblM_RoleGroup { get; set; }
        public virtual DbSet<tblM_Status> tblM_Status { get; set; }
        public virtual DbSet<tblM_User> tblM_User { get; set; }
        public virtual DbSet<tblM_UserDetail> tblM_UserDetail { get; set; }
        public virtual DbSet<tblT_AsetHistori> tblT_AsetHistori { get; set; }
        public virtual DbSet<tblT_CheckIn> tblT_CheckIn { get; set; }
        public virtual DbSet<tblT_Cost> tblT_Cost { get; set; }
        public virtual DbSet<tblT_IzinCuti> tblT_IzinCuti { get; set; }
        public virtual DbSet<tblT_SOW> tblT_SOW { get; set; }
        public virtual DbSet<tblT_SOWAssign> tblT_SOWAssign { get; set; }
        public virtual DbSet<tblT_SOWTrack> tblT_SOWTrack { get; set; }
        public virtual DbSet<tblT_UserHistori> tblT_UserHistori { get; set; }
        public virtual DbSet<tblT_UserPayroll> tblT_UserPayroll { get; set; }
    }
}
