//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_BTS
    {
        public int BTS_PK { get; set; }
        public string CustomerSite { get; set; }
        public string TowerID { get; set; }
        public string CellID { get; set; }
        public string Name { get; set; }
        public int Operator_FK { get; set; }
        public Nullable<int> StatusBTS_FK { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int Area_FK { get; set; }
        public string Alamat { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Status_FK { get; set; }
    }
}
