
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GlobalSolusindo.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class tblM_Status
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblM_Status()
    {

        this.tblM_Aset = new HashSet<tblM_Aset>();

        this.tblM_AsetKategori = new HashSet<tblM_AsetKategori>();

        this.tblM_AuthParam = new HashSet<tblM_AuthParam>();

        this.tblM_Cabang = new HashSet<tblM_Cabang>();

        this.tblM_Kota = new HashSet<tblM_Kota>();

        this.tblM_MappingRoleToRoleGroup = new HashSet<tblM_MappingRoleToRoleGroup>();

        this.tblM_MappingUserToAuthParam = new HashSet<tblM_MappingUserToAuthParam>();

        this.tblM_MappingUserToRoleGroup = new HashSet<tblM_MappingUserToRoleGroup>();

        this.tblM_Role = new HashSet<tblM_Role>();

        this.tblT_AsetHistori = new HashSet<tblT_AsetHistori>();

        this.tblM_User = new HashSet<tblM_User>();

        this.tblM_UserDetail = new HashSet<tblM_UserDetail>();

        this.tblT_UserHistori = new HashSet<tblT_UserHistori>();

    }


    public int Status_PK { get; set; }

    public string Title { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_Aset> tblM_Aset { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_AsetKategori> tblM_AsetKategori { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_AuthParam> tblM_AuthParam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_Cabang> tblM_Cabang { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_Kota> tblM_Kota { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_MappingRoleToRoleGroup> tblM_MappingRoleToRoleGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_MappingUserToAuthParam> tblM_MappingUserToAuthParam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_MappingUserToRoleGroup> tblM_MappingUserToRoleGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_Role> tblM_Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblT_AsetHistori> tblT_AsetHistori { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_User> tblM_User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_UserDetail> tblM_UserDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblT_UserHistori> tblT_UserHistori { get; set; }

}

}
