//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblM_UserDetail()
        {
            this.tblM_User = new HashSet<tblM_User>();
            this.tblT_AsetHistori = new HashSet<tblT_AsetHistori>();
            this.tblT_UserHistori = new HashSet<tblT_UserHistori>();
        }
    
        public int UserDetail_PK { get; set; }
        public string UserCode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TglLahir { get; set; }
        public byte[] FilePhoto { get; set; }
        public string NoKTP { get; set; }
        public string NoHP { get; set; }
        public string Email { get; set; }
        public string PersonalEmail { get; set; }
        public string Address { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Status_FK { get; set; }
    
        public virtual tblM_Status tblM_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblM_User> tblM_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblT_AsetHistori> tblT_AsetHistori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblT_UserHistori> tblT_UserHistori { get; set; }
    }
}
