
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GlobalSolusindo.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class tblM_AsetKategori
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblM_AsetKategori()
    {

        this.tblM_Aset = new HashSet<tblM_Aset>();

    }


    public int AsetKategori_PK { get; set; }

    public string Title { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public int Status_FK { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblM_Aset> tblM_Aset { get; set; }

    public virtual tblM_Status tblM_Status { get; set; }

}

}
