//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_LogActivity
    {
        public int LogActivity_PK { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> ActivityDateTime { get; set; }
        public string ActivityName { get; set; }
        public string ActivityKey { get; set; }
        public string ActivityResult { get; set; }
        public string ActivityDescription { get; set; }
        public string ValueOld { get; set; }
        public string ValueNew { get; set; }
    }
}
