//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;

    public partial class tblT_UserPayroll
    {
        public int UserPayroll_PK { get; set; }
        public int UserDetail_FK { get; set; }
        public decimal Nominal { get; set; }
        public System.DateTime TglMulai { get; set; }
        public Nullable<System.DateTime> TglSelesai { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Status_FK { get; set; }
    }
}
