//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_PO
    {
        public int PO_PK { get; set; }
        public string Account { get; set; }
        public string ProjectCode { get; set; }
        public string SiteIDImp { get; set; }
        public string SiteID { get; set; }
        public string SiteName { get; set; }
        public string DUID { get; set; }
        public string PMOUniq { get; set; }
        public string SOWAct { get; set; }
        public string System { get; set; }
        public string SOWPO { get; set; }
        public string ItemDesc { get; set; }
        public string PONo { get; set; }
        public string ShipmentNo { get; set; }
        public int Qty { get; set; }
        public string POStatus { get; set; }
        public string PaymentTerm { get; set; }
        public string WorkStatus { get; set; }
        public Nullable<System.DateTime> OADate { get; set; }
        public Nullable<System.DateTime> SSVDate { get; set; }
        public Nullable<System.DateTime> SSVAppDate { get; set; }
        public Nullable<System.DateTime> SOMSSVDate { get; set; }
        public Nullable<System.DateTime> QCAccDate { get; set; }
        public string PACClusterID { get; set; }
        public string PACClusterStatus { get; set; }
        public string SOMPACCluster { get; set; }
        public string DocStatus { get; set; }
        public string ESAR1stStatus { get; set; }
        public string ESAR2ndStatus { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Status_FK { get; set; }
    }
}
