
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GlobalSolusindo.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class tblT_Cost
{

    public int Cost_PK { get; set; }

    public Nullable<int> KategoriCost_FK { get; set; }

    public Nullable<int> SOW_FK { get; set; }

    public double Nominal { get; set; }

    public string Deskripsi { get; set; }

    public Nullable<System.DateTime> Tanggal { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public int Status_FK { get; set; }

}

}
