//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SOWLink
    {
        public int SOW_PK { get; set; }
        public string RNO { get; set; }
        public string LinkRNO { get; set; }
        public string RF { get; set; }
        public string LinkRF { get; set; }
        public string Rigger { get; set; }
        public string LinkRigger { get; set; }
        public string DT { get; set; }
        public string SSVLink { get; set; }
        public string SSOLink { get; set; }
        public int Status_FK { get; set; }
    }
}
