//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSolusindo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SOWIssue
    {
        public int SOWAssign_PK { get; set; }
        public Nullable<int> IssueType_FK { get; set; }
        public string IssueName { get; set; }
        public Nullable<int> SOW_FK { get; set; }
        public Nullable<int> User_FK { get; set; }
        public int KategoriJabatan_PK { get; set; }
        public string Title { get; set; }
    }
}
